export const NAV_LINKS = [
  { label: "About", href: "#hero" },
  { label: "Skills", href: "#skills" },
  { label: "Projects", href: "#projects" },
  { label: "Education", href: "#education" },
  { label: "Contact", href: "#contact" },
];

export const SOCIAL_LINKS = {
  github: "https://github.com/vikal230",
  linkedin: "https://www.linkedin.com/in/vikal-saini-546119339/",
  email: "vikalsaini06@gmail.com",
};

export const SKILLS = {
  Frontend: [
    "HTML",
    "CSS",
    "JavaScript (ES6+)",
    "TypeScript",
    "React.js",
    "Next.js",
    "Redux Toolkit",
    "Tailwind CSS",
    "SASS",
    "Bootstrap",
  ],
  Backend: [
    "Node.js",
    "Express.js",
    "REST API",
    "JWT Auth",
    "Socket.IO",
    "Multer",
    "Nodemailer",
  ],
  Database: ["MongoDB", "Mongoose", "Firebase", "MySQL"],
  "Gen AI & Tools": [
    "Google Gemini API",
    "Ollama (Local LLM)",
    "Prompt Engineering",
    "Zod",
    "Git",
    "GitHub",
    "Postman",
    "Cloudinary",
    "Razorpay",
    "Puppeteer",
    "Vite",
  ],
};

export const SKILL_ICONS: Record<string, string> = {
  Frontend: "🎨",
  Backend: "⚙️",
  Database: "🗄️",
  "Gen AI & Tools": "🤖",
};

export const PROJECTS = [
  {
    id: 1,
    title: "Resume Analyzer",
    subtitle: "with Gemini AI",
    description:
      "AI-powered resume analyzer that parses PDFs using pdf-parse, identifies skill-gaps via Gemini API, secures sessions with JWT in HTTP-only cookies, generates PDF reports with Puppeteer, and enforces strict type-safety using Zod schemas for AI output validation.",
    tags: [
      "React.js",
      "Java Script",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Gemini API",
      "Puppeteer",
      "JWT",
      "SCSS",
      "pdf-parse",
      "Zod",
    ],
    color: "from-violet-500/20 to-indigo-500/10",
    border: "border-violet-500/20",
    accent: "#8b5cf6",
    liveUrl: "https://ai-powered-resume-analyzer-mu.vercel.app/",
    sourceUrl: "https://github.com/vikal230/AI-Powered-Resume-Analyzer.git",
    highlights: [
      "PDF Parsing",
      "AI Skill-Gap Analysis",
      "JWT HTTP-only Cookies",
      "Puppeteer PDF Export",
    ],
  },
  {
    id: 2,
    title: "Ekart",
    subtitle: "Full Stack E-Commerce",
    description:
      "A 3-app ecosystem (Customer, Admin, Delivery) sharing one MongoDB backend. Features server-side Razorpay payment integration, Google Auth via Firebase, Cloudinary for media uploads, and a Gemini-powered AI chatbot with dual customer/admin modes using live catalog data.",
    tags: [
      "React.js",
      "Java Script",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Razorpay",
      "Firebase",
      "Cloudinary",
      "Gemini AI",
      "JWT",
    ],
    color: "from-cyan-500/20 to-teal-500/10",
    border: "border-cyan-500/20",
    accent: "#06b6d4",
    liveUrl: "https://ekart-fullstack.vercel.app",
    adminUrl: "https://ekart-fullstack-nk4n.vercel.app",
    sourceUrl: "https://github.com/vikal230/ekart-fullstack.git",
    highlights: [
      "3-App Ecosystem",
      "Razorpay Payments",
      "Firebase Google Auth",
      "AI Chatbot",
    ],
  },
  {
    id: 3,
    title: "Curalink",
    subtitle: "AI Medical Research Assistant",
    description:
      "Evidence-grounded medical assistant that pulls real-time research from PubMed & OpenAlex APIs. Generates cited answers using a local LLM via Ollama, backed by MongoDB multi-turn session memory, with intelligent partial-source fallback handling for robust responses.",
    tags: [
      "React.js",
      "Java Script",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Ollama (Local LLM)",
      "PubMed",
      "OpenAlex",
      "ClinicalTrials.gov",
      "Tailwind CSS",
    ],
    color: "from-emerald-500/20 to-green-500/10",
    border: "border-emerald-500/20",
    accent: "#10b981",
    liveUrl: "https://curalink-pearl.vercel.app/",
    sourceUrl: "https://github.com/vikal230/curalink.git",
    highlights: [
      "Local LLM (Ollama)",
      "PubMed + OpenAlex APIs + ClinicalTrials.gov",
      "Session Memory",
      "Cited Answers",
    ],
  },
  {
    id: 4,
    title: "Hype",
    subtitle: "Social Media Platform",
    description:
      "Feature-complete social app with posts, reels, stories, and real-time chat powered by Socket.IO — including online presence tracking and instant notifications. Built with OTP-based password reset via Nodemailer and Redux Toolkit for predictable global state.",
    tags: [
      "Tailwind CSS",
      "React.js",
      "Java Script",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.IO",
      "Redux Toolkit",
      "JWT",
      "Nodemailer",
    ],
    color: "from-rose-500/20 to-pink-500/10",
    border: "border-rose-500/20",
    accent: "#f43f5e",
    liveUrl: "https://connect-hub-wine.vercel.app",
    sourceUrl: "https://github.com/vikal230/connect-hub.git",
    highlights: [
      "Socket.IO Real-Time Chat",
      "Online Presence Tracking",
      "OTP Password Reset",
      "Redux State",
    ],
  },
];

export const EDUCATION = {
  degree: "Bachelor of Computer Applications (BCA)",
  university: "IFTM University",
  period: "2023 – 2026",
  cgpa: "7.75 / 10",
  subjects: [
    "Data Structures",
    "Web Development",
    "JavaScript",
    "Object-Oriented Programming",
  ],
};
